### ISSUE TITLE
Failed to activate the Clean package

### ISSUE THREAD

**Issue by jdtonkin** [andytlr/clean#7]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [Clean](https://github.com/andytlr/clean) package, v0.10.0
### Stack Trace

Failed to activate the Clean package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
  at Object.module.exports.activate (/Users/jonathantonkin/.atom/packages/Clean/lib/clean.coffee:3:23)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:245:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:838:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:226:20)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```
### Commands

```
  3x -1:02.2.0 clean:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-material-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Clean, v0.10.0
atom-material-syntax, v0.2.4
color-picker, v2.0.12
language-latex, v0.6.1
language-r, v0.2.0
latex, v0.25.1
minimap, v4.13.4
terminal-panel, v1.14.1
wordcount, v2.3.0

# Dev
No dev packages
```

**Comment by open-sourceress** [comment]
+1 with Atom 1.4.0 on Win7

**Comment by Yoshi325** [comment]
+1 with Atom 1.21.1 on macOS

**Comment by Sillu129092** [comment]
fgfgf

**Comment by Sillu129092** [comment]
atom://teletype/portal/b51728f0-f3da-4273-878a-abbaa7e9f725
